In [1]:

import os
from bs4 import BeautifulSoup
import re
import emoji
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
def load_dict_smileys():
  return {
        ":‑)":"gülücük",
        ":-]":"gülücük",
        ":-3":"gülücük",
        ":->":"gülücük",
        "8-)":"gülücük",
        ":-}":"gülücük",
        ":)":"gülücük",
        ":]":"gülücük",
        ":3":"gülücük",
        ":>":"gülücük",
        "8)":"gülücük",
        ":}":"gülücük",
        ":o)":"gülücük",
        ":c)":"gülücük",
        ":^)":"gülücük",
        "=]":"gülücük",
        "=)":"gülücük",
        ":-))":"gülücük",
        ":‑D":"gülücük",
        "8‑D":"gülücük",
        "x‑D":"gülücük",
        "X‑D":"gülücük",
        ":D":"gülücük",
        "8D":"gülücük",
        "xD":"gülücük",
        "XD":"gülücük",
        ":‑(":"üzgün",
        ":‑c":"üzgün",
        ":‑<":"üzgün",
        ":‑[":"üzgün",
        ":(":"üzgün",
        ":c":"üzgün",
        ":<":"üzgün",
        ":[":"üzgün",
        ":-||":"üzgün",
        ">:[":"üzgün",
        ":{":"üzgün",
        ":@":"üzgün",
        ">:(":"üzgün",
        ":'‑(":"üzgün",
        ":'(":"üzgün",
        ":‑P":"eğlenceli",
        "X‑P":"eğlenceli",
        "x‑p":"eğlenceli",
        ":‑p":"eğlenceli",
        ":‑Þ":"eğlenceli",
        ":‑þ":"eğlenceli",
        ":‑b":"eğlenceli",
        ":P":"eğlenceli",
        "XP":"eğlenceli",
        "xp":"eğlenceli",
        ":p":"eğlenceli",
        ":Þ":"eğlenceli",
        ":þ":"eğlenceli",
        ":b":"eğlenceli",
        "<3":"sevgi"
        }
def cumleyiarindir(tweet):
    tweet = BeautifulSoup(tweet).get_text()
    #Special case not handled previously.
    tweet = tweet.replace('\x92',"'")
    #Removal of hastags/account
    tweet = ' '.join(re.sub("(@[A-Za-z0-9]+)|(#[A-Za-z0-9]+)", " ", tweet).split())
    #Removal of address
    tweet = ' '.join(re.sub("(\w+:\/\/\S+)", " ", tweet).split())
    #Removal of Punctuation
    tweet = ' '.join(re.sub("[\.\,\!\?\:\;\-\=]", " ", tweet).split())
    #Lower case
    tweet = tweet.lower()
    SMILEY = load_dict_smileys()  
    words = tweet.split()
    reformed = [SMILEY[word] if word in SMILEY else word for word in words]
    tweet = " ".join(reformed)
    #Deal with emojis
    tweet = emoji.demojize(tweet)
    #Strip accents
   
    tweet = tweet.replace(":"," ")
    tweet = ' '.join(tweet.split())
    return tweet

In [3]:
sentences=[]
labels=[]

#folders=[ '1','2', '3','4','5', '6','7','8', '9','10','11', '12','13','14', '15','16','17', '18','19','20']
folders=[ '1','2', '3'] 
filename='/Users/hp7tron/MakineOgrenmesiFinal/raw_texts'
for x in folders:
    tweet_count=0 
    path=os.path.join(filename, x)        
    for t in os.listdir(path):
        tweet_count+=1   
        p2=os.path.join(path,t)          
        with open(p2, 'rb') as f:
            text = f.read()
            text=cumleyiarindir(text)
        sentences.append(text)
        labels.append(x)  
        f.close()
    print(x,'. Klasör tweet sayısı :',tweet_count)


1 . Klasör tweet sayısı : 756
2 . Klasör tweet sayısı : 1287
3 . Klasör tweet sayısı : 957


In [9]:
fp = open('mail.csv','wt',encoding='utf8')
for i in range(len(sentences)):
    newSentence = sentences[i]+'\n'
    fp.write(newSentence)
fp.close() 

fp = open('maillabellat.csv','wt',encoding='utf8')
for i in range(len(labels)):
    newSentence = labels[i]+'\n'
    fp.write(newSentence)
fp.close() 


In [48]:
import pandas as pd 
#tweetdata.csv
#calisirmilan.csv   nan değerler silindi 
#tweetdata2.csv sep=; parametresini kaldır 

csvname ='stsGold.txt'
data  = pd.read_csv(csvname ,sep=',' , engine='python')
print(data)


'''
import numpy as np
data.columns=['cumle','etiket']
index = data['cumle'].index[data['cumle'].apply(pd.isnull)]
print(index[0])
find = data.any 1036,1405,7694,18230,
print(find) 545,1004,1006,1008,1035,1403,7691,9800,18226
import numpy as np a.bool(), a.item(), a.any()
df1 = data.replace(np.nan, '', regex=True)'''

      oz0  oz1  oz2  oz3       oz4  oz5  oz6  oz7  oz8       oz9  ...  oz2513  \
0     0.0  0.0  0.0  0.0  1.028098  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
1     0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
2     0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
3     0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
4     0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
...   ...  ...  ...  ...       ...  ...  ...  ...  ...       ...  ...     ...   
1330  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
1331  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.686797  ...     0.0   
1332  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
1333  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   
1334  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  ...     0.0   

      oz2514  oz2515  oz251

"\nimport numpy as np\ndata.columns=['cumle','etiket']\nindex = data['cumle'].index[data['cumle'].apply(pd.isnull)]\nprint(index[0])\nfind = data.any 1036,1405,7694,18230,\nprint(find) 545,1004,1006,1008,1035,1403,7691,9800,18226\nimport numpy as np a.bool(), a.item(), a.any()\ndf1 = data.replace(np.nan, '', regex=True)"

In [49]:
#sentences = [ doc for doc in data.iloc[:,0]]
#labels = [ doc for doc in data.iloc[:,1]]
sentences= data.iloc[:,:-1]
labels=data['twitLabels']


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer='word',lowercase = True)
deneme = vectorizer.fit_transform(sentences)




In [17]:
X_train,X_test,y_train,y_test=train_test_split(deneme,labels,test_size=0.80,random_state=38)


In [18]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
classifier= MultinomialNB() #classifier nesnesi oluşturdum
model = classifier.fit(X_train, y_train)

In [19]:
predictions=model.predict(X_test)
print(predictions)

['2' '2' '2' ... '2' '2' '2']


In [20]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[  71  509   19]
 [   6 1013    3]
 [  28  704   47]]
              precision    recall  f1-score   support

           1       0.68      0.12      0.20       599
           2       0.46      0.99      0.62      1022
           3       0.68      0.06      0.11       779

    accuracy                           0.47      2400
   macro avg       0.60      0.39      0.31      2400
weighted avg       0.58      0.47      0.35      2400

